Use `curl` to fetch ephemerides on Travis CI
Builds are failing with Python errors like:
```
IOError: cannot get http://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/satellites/jup310.bsp because <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:581)>
```
So if their version of Python cannot do the SSL, let's try `curl`.