Make Time whole and fraction have same dimensions
Otherwise, `.utc_jpl()` was dying with:
```
  File "/home/brandon/skyfield/skyfield/timelib.py", line 520, in utc_jpl
    return format % args
TypeError: %d format: a number is required, not numpy.ndarray
```