Fix: new `Stack` needs to remember its ephemeris
To find the position of deflectors like the Sun and Jupiter, the
`.observe()` method uses its position’s `._ephemeris`, which is in turn
copied from the vector function’s `.ephemeris`.  But I had forgotten to
record an `.ephemeris` for the new `jpllib.Stack`, so users saw:

    File ".../skyfield/relativity.py", line 46, in add_deflection
      deflector = ephemeris[name]
                  ~~~~~~~~~^^^^^^
    TypeError: 'NoneType' object is not subscriptable

Fixes #1063. Fixes #1066. Fixes #1068.