Make it possible to str() a vector Distance
Without this tweak, the attempt to print was dying with an error,
because a NumPy array does not know what to do with a '.6' format
string:

Traceback (most recent call last):
  File "tmp9.py", line 9, in <module>
      print(mars(tt=2457061.5).position)
        File "/home/brandon/skyfield/skyfield/units.py", line 50, in
  __str__
      return '{0:.6} AU'.format(self.AU)
      TypeError: non-empty format string passed to object.__format__

In response I have opened: https://github.com/numpy/numpy/issues/5543