Fix `find_discrete()` when start + end are close
Fixes #240 where, previously, a start time and end time closer together
than a rough period would result in an empty array of times to search,
resulting in errors in the actual astronomy code like:

```
ValueError: zero-size array to reduction operation minimum which has no identity
```