Upgrade development environment to Python 3.7
Last year I tried jumping to the most recent Python; the result was a
disaster.  But let’s try at least jumping to 3.7, so that I can switch
to `uv python install` instead of the old `pyenv`.  Fingers crossed.
The `jinja2` downgrade is to avoid the error:

    Could not import extension sphinx.builders.latex
    (exception: cannot import name 'contextfunction' from 'jinja2'...)