Remove Python 3.3 from Travis, since pip errors
It looks like pip no longer likes Python 3.3?
```
RuntimeError: Python 3.4 or later is required
The command "pip install $(echo ../dist/skyfield-*.tar.gz)'[tests]'" failed and exited with 1 during .
```